Linked to more Python examples
zxing-cpp/zxing-cpp pull request #487
Opened 2023-01-14 20:18 UTC by PanderMusubi

Adding this link is useful for e.g. https://pypi.org/project/zxing-cpp/

2023-01-16 08:17 UTC, axxel commented
What examples did you have in mind here?

2023-01-17 15:15 UTC, PanderMusubi commented
I have amended the commit. Please review that one. The demo files have been improved and their code was added to the README.

2023-01-18 09:13 UTC, axxel commented
Thanks for your offer to help improve the code. I agree with adding a writing sample to the README and I also agree that the new string interpolation syntax is nicer to read. I don't like the additional line breaks and the removal of the explicit `zxingcpp.` qualification of the function names, though. Also the change from cv2 to PIL makes some sense, I would like to see a comment showing the `cv2.imread(...)` alternative as a lot of people seem to be using cv2.

Would you mind updating that PR once more?

2023-01-18 11:52 UTC, PanderMusubi commented
Yes, no problem

2023-01-18 14:20 UTC, axxel requested changes
The " -> ' replacement does increase the consistency. Thanks for that.

Hopefully we can wrap this up with the next try (If you are inclined to put even more of your time into this ;)).

2023-01-18 14:20 UTC, axxel commented on wrappers/python/README.md
> +                                 'I have the best words.', width=200, height=200)
I should have been more precise before: I meant those line-breaks...

2023-01-18 14:20 UTC, axxel commented on wrappers/python/README.md
> +img = imread(sys.argv[1])
Please keep the module name here as well. For this type of "show someone at a glance what it going on" purpose I believe that helps in understanding the code more quickly. I also think using PIL here is maybe even more "basic" but thought that a comment would be useful:
```
img = Image.open(sys.argv[1])   # or using OpenCV: cv2.imread(sys.argv[1])
```

2023-01-18 14:44 UTC, PanderMusubi commented
Yes, no worries. Will rework your feedback.

For the rest good to know Python linters such as flake are steering more and more in direction of using 4 spaces instead of tabs. See also https://www.google.com/search?hl=en&q=python%20tabs%20spaces

2023-03-28 07:35 UTC, axxel commented
> Yes, no worries. Will rework your feedback.

Just wondering: are you waiting on input from me here?

2023-03-28 09:37 UTC, PanderMusubi commented
Sorry for the delay, it is on my list and will contribute next week.

2023-04-19 15:25 UTC, PanderMusubi commented
I hope all your feedback has not been resolved. The documentation and Python scripts are very dummy proof. Let me know if this is what you expected.

2023-04-20 10:32 UTC, axxel requested changes
Thanks for picking this up again. There are still unresolved comments from earlier and you introduced new changes that I find questionable. I went ahead and reviewed this one more time, trying to address everything. Let's give this one last try. ;)

2023-04-20 10:32 UTC, axxel commented on wrappers/python/README.md
> +pip install --upgrade zxing-cpp
Introducing more changes is not helping with getting this merged, I fear ;).

2023-04-20 10:32 UTC, axxel commented on wrappers/python/README.md
> -[Note: To install via `setup.py` (or via `pip install` in case there is no pre-build wheel available for your platfor or python version), you need a suitable [build environment](https://github.com/zx
The `[Note: ...]` brackets are a stylistic choice used in other readmeas as well. Please leave them alone.

2023-04-20 10:32 UTC, axxel commented on wrappers/python/README.md
> +	img = zxingcpp.zxingcwrite_barcode(zxingcpp.barcode_format_from_str(sys.argv[1]),
`zxingcwrite_barcode` method does not exists. To make this as simple as possible, please leave only the first `if` branch.

2023-04-20 10:32 UTC, axxel commented on wrappers/python/README.md
> +#	img = Image.open(sys.argv[1])
Please keep this as one line (see my earlier review comment). This README sample code is supposed to be as simple as it gets while giving an idea how the code works.

2023-04-20 10:32 UTC, axxel commented on wrappers/python/demo_reader.py
> +#	img = Image.open(sys.argv[1])
Same here, please revert all changes in this file above the `print(` line below.

2023-04-20 10:32 UTC, axxel commented on wrappers/python/demo_writer.py
> +	img = zxingcpp.zxingcwrite_barcode(zxingcpp.barcode_format_from_str(sys.argv[1]),
this code will not run, see above. Also as mentioned in earlier review: please revert every change except the `"` -> `'` replacement.

2023-04-20 10:32 UTC, axxel commented on wrappers/python/test.py
> +        self.assertEqual(zxingcpp.barcode_formats_from_str('ITF, qrcode'), BF.ITF | BF.QRCode)
As mentioned before, please don't change the whitespace.

2023-04-20 14:04 UTC, axxel commented
Note: if you should give it a last try, please merge with HEAD first as some `test.py` lines have changed.

2023-04-20 16:37 UTC, PanderMusubi commented
Will do. Thanks for the feedback.

2023-04-28 16:46 UTC, PanderMusubi commented
I will make a new PR for this as there are too many git conflicts and resolve attempts on feedback that I also lost track of all the details.

2023-04-28 16:46 UTC, closed without merging

2023-09-08 21:40 UTC, axxel commented
Thanks for looking into this once more. I decided to do these trivial changes directly because communicating my preferences would have taken about as much of my time plus yours to implement them...